---
settings:
  # color_bar:   "#fff"
  # color_label: "#eee"
  # color_text:  "#fff"
  # decoration: false
  # resizable: false
  # skip_taskbar: true
  # color_background: "#000"
  # font_size: large
  timeout: 1
  # xpos: 3380
  # ypos: 0

ui:
  - text: SYSTEM
    type: system
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_speed_rpi
        text: "CPU speed:"

      - func: cpu_temp_sys
        text: "CPU Temp:"

      - func: cpu_voltage_rpi
        text: "CPU voltage:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

  - text: FILESYSTEM
    type: filesystem
    items:
      - text: "root:"
        mount_point: /
